// <auto-generated />
using System;
using EmployeeManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("EmployeeSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 502036,
                            EmployeeCode = "EMP326",
                            EmployeeName = "Selim Reja",
                            EmployeeSalary = 59000m
                        },
                        new
                        {
                            EmployeeId = 502030,
                            EmployeeCode = "EMP320",
                            EmployeeName = "Mehedi Hasan",
                            EmployeeSalary = 50000m,
                            SupervisorId = 502036
                        },
                        new
                        {
                            EmployeeId = 502031,
                            EmployeeCode = "EMP321",
                            EmployeeName = "Ashikur Rahman",
                            EmployeeSalary = 45000m,
                            SupervisorId = 502036
                        },
                        new
                        {
                            EmployeeId = 502032,
                            EmployeeCode = "EMP322",
                            EmployeeName = "Rakibul Islam",
                            EmployeeSalary = 52000m,
                            SupervisorId = 502030
                        },
                        new
                        {
                            EmployeeId = 502033,
                            EmployeeCode = "EMP323",
                            EmployeeName = "Hasan Abdullah",
                            EmployeeSalary = 46000m,
                            SupervisorId = 502031
                        },
                        new
                        {
                            EmployeeId = 502034,
                            EmployeeCode = "EMP324",
                            EmployeeName = "Akib Khan",
                            EmployeeSalary = 66000m,
                            SupervisorId = 502032
                        },
                        new
                        {
                            EmployeeId = 502035,
                            EmployeeCode = "EMP325",
                            EmployeeName = "Rasel Shikder",
                            EmployeeSalary = 53500m,
                            SupervisorId = 502033
                        });
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.EmployeeAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOffday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("EmployeeAttendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 2,
                            AttendanceDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 3,
                            AttendanceDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 4,
                            AttendanceDate = new DateTime(2023, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 5,
                            AttendanceDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 6,
                            AttendanceDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 7,
                            AttendanceDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 8,
                            AttendanceDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 9,
                            AttendanceDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 10,
                            AttendanceDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 11,
                            AttendanceDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 12,
                            AttendanceDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 13,
                            AttendanceDate = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 14,
                            AttendanceDate = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 15,
                            AttendanceDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 16,
                            AttendanceDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 17,
                            AttendanceDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 18,
                            AttendanceDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 19,
                            AttendanceDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 20,
                            AttendanceDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 21,
                            AttendanceDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 22,
                            AttendanceDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 23,
                            AttendanceDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 24,
                            AttendanceDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 25,
                            AttendanceDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 26,
                            AttendanceDate = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 27,
                            AttendanceDate = new DateTime(2023, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 28,
                            AttendanceDate = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 29,
                            AttendanceDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 30,
                            AttendanceDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502030,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 31,
                            AttendanceDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 32,
                            AttendanceDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 33,
                            AttendanceDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 34,
                            AttendanceDate = new DateTime(2023, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 35,
                            AttendanceDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 36,
                            AttendanceDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = true,
                            IsOffday = false,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 37,
                            AttendanceDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 38,
                            AttendanceDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 39,
                            AttendanceDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 40,
                            AttendanceDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 41,
                            AttendanceDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 42,
                            AttendanceDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 43,
                            AttendanceDate = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 44,
                            AttendanceDate = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 45,
                            AttendanceDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 46,
                            AttendanceDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 47,
                            AttendanceDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 48,
                            AttendanceDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 49,
                            AttendanceDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 50,
                            AttendanceDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 51,
                            AttendanceDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 52,
                            AttendanceDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 53,
                            AttendanceDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 54,
                            AttendanceDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 55,
                            AttendanceDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 56,
                            AttendanceDate = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = true,
                            IsOffday = false,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 57,
                            AttendanceDate = new DateTime(2023, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 58,
                            AttendanceDate = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 59,
                            AttendanceDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 60,
                            AttendanceDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502031,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 61,
                            AttendanceDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 62,
                            AttendanceDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 63,
                            AttendanceDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 64,
                            AttendanceDate = new DateTime(2023, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 65,
                            AttendanceDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 66,
                            AttendanceDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 67,
                            AttendanceDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 68,
                            AttendanceDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 69,
                            AttendanceDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 70,
                            AttendanceDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 71,
                            AttendanceDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 72,
                            AttendanceDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 73,
                            AttendanceDate = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 74,
                            AttendanceDate = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 75,
                            AttendanceDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 76,
                            AttendanceDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 77,
                            AttendanceDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 78,
                            AttendanceDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 79,
                            AttendanceDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 80,
                            AttendanceDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 81,
                            AttendanceDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 82,
                            AttendanceDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 83,
                            AttendanceDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 84,
                            AttendanceDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 85,
                            AttendanceDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 86,
                            AttendanceDate = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 87,
                            AttendanceDate = new DateTime(2023, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 88,
                            AttendanceDate = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 89,
                            AttendanceDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 90,
                            AttendanceDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502032,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 91,
                            AttendanceDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 92,
                            AttendanceDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 93,
                            AttendanceDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 94,
                            AttendanceDate = new DateTime(2023, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 95,
                            AttendanceDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 96,
                            AttendanceDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = true,
                            IsOffday = false,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 97,
                            AttendanceDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 98,
                            AttendanceDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 99,
                            AttendanceDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 100,
                            AttendanceDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 101,
                            AttendanceDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 102,
                            AttendanceDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 103,
                            AttendanceDate = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 104,
                            AttendanceDate = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 105,
                            AttendanceDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 106,
                            AttendanceDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 107,
                            AttendanceDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 108,
                            AttendanceDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 109,
                            AttendanceDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 110,
                            AttendanceDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 111,
                            AttendanceDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 112,
                            AttendanceDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 113,
                            AttendanceDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 114,
                            AttendanceDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 115,
                            AttendanceDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 116,
                            AttendanceDate = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = true,
                            IsOffday = false,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 117,
                            AttendanceDate = new DateTime(2023, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 118,
                            AttendanceDate = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 119,
                            AttendanceDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 120,
                            AttendanceDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502033,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 121,
                            AttendanceDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 122,
                            AttendanceDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 123,
                            AttendanceDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 124,
                            AttendanceDate = new DateTime(2023, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 125,
                            AttendanceDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 126,
                            AttendanceDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 127,
                            AttendanceDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 128,
                            AttendanceDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 129,
                            AttendanceDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 130,
                            AttendanceDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 131,
                            AttendanceDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 132,
                            AttendanceDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 133,
                            AttendanceDate = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 134,
                            AttendanceDate = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 135,
                            AttendanceDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 136,
                            AttendanceDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 137,
                            AttendanceDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 138,
                            AttendanceDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 139,
                            AttendanceDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 140,
                            AttendanceDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 141,
                            AttendanceDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 142,
                            AttendanceDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 143,
                            AttendanceDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 144,
                            AttendanceDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 145,
                            AttendanceDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 146,
                            AttendanceDate = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 147,
                            AttendanceDate = new DateTime(2023, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 148,
                            AttendanceDate = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 149,
                            AttendanceDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 150,
                            AttendanceDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502034,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 151,
                            AttendanceDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 152,
                            AttendanceDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 153,
                            AttendanceDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 154,
                            AttendanceDate = new DateTime(2023, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 155,
                            AttendanceDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 156,
                            AttendanceDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = true,
                            IsOffday = false,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 157,
                            AttendanceDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 158,
                            AttendanceDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 159,
                            AttendanceDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 160,
                            AttendanceDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 161,
                            AttendanceDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 162,
                            AttendanceDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 163,
                            AttendanceDate = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 164,
                            AttendanceDate = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 165,
                            AttendanceDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 166,
                            AttendanceDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 167,
                            AttendanceDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 168,
                            AttendanceDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 169,
                            AttendanceDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 170,
                            AttendanceDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 171,
                            AttendanceDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 172,
                            AttendanceDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 173,
                            AttendanceDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 174,
                            AttendanceDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 175,
                            AttendanceDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 176,
                            AttendanceDate = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = true,
                            IsOffday = false,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 177,
                            AttendanceDate = new DateTime(2023, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 178,
                            AttendanceDate = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 179,
                            AttendanceDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 180,
                            AttendanceDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502035,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 181,
                            AttendanceDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 182,
                            AttendanceDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 183,
                            AttendanceDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 184,
                            AttendanceDate = new DateTime(2023, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 185,
                            AttendanceDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 186,
                            AttendanceDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = true,
                            IsOffday = false,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 187,
                            AttendanceDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 188,
                            AttendanceDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 189,
                            AttendanceDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 190,
                            AttendanceDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 191,
                            AttendanceDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 192,
                            AttendanceDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 193,
                            AttendanceDate = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 194,
                            AttendanceDate = new DateTime(2023, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 195,
                            AttendanceDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 196,
                            AttendanceDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 197,
                            AttendanceDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 198,
                            AttendanceDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 199,
                            AttendanceDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 200,
                            AttendanceDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 201,
                            AttendanceDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 202,
                            AttendanceDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 203,
                            AttendanceDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 204,
                            AttendanceDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 205,
                            AttendanceDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 206,
                            AttendanceDate = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = true,
                            IsOffday = false,
                            IsPresent = false
                        },
                        new
                        {
                            Id = 207,
                            AttendanceDate = new DateTime(2023, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 208,
                            AttendanceDate = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 209,
                            AttendanceDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = false,
                            IsPresent = true
                        },
                        new
                        {
                            Id = 210,
                            AttendanceDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 502036,
                            IsAbsent = false,
                            IsOffday = true,
                            IsPresent = false
                        });
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Employee", b =>
                {
                    b.HasOne("EmployeeManagementAPI.Models.Employee", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.EmployeeAttendance", b =>
                {
                    b.HasOne("EmployeeManagementAPI.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
